name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      python_release_version:
        description: "Python version to use for build and publish"
        required: false
        default: "3.12"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pypi.org/p/deltastream-sdk
    permissions:
      id-token: write # for trusted publishing without token/secret
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python for Release
        uses: actions/setup-python@v4
        with:
          python-version: "${{ github.event.inputs.python_release_version || '3.12' }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-packages
      - name: Test with pytest for release
        run: |
          uv run pytest
      - name: Test build
        run: |
          uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
